### PR TITLE
add dummy item to items collection

### PR DESCRIPTION
**Pull request by iamdror**
# Description
this is an addition to new env startup, we want to be able to easily add items to items list to get things started easily 

## Type of change

- [x] New feature

# How Has This Been Tested?
1. start local env
2. `docker exec -it anythink-backend bash` in a new terminal tab
3. cd to backend folder
4. run `./seed.sh`
5. open UI on web browser and make sure a new item with title "title" was created

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
That was fast! Thanks for the PR @iamdror, I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Umm, something is off. Make sure all checks pass and only then try and merge the PR.

**Comment by iamdror** [comment]
@vanessa-cooper all checks pass

**Review by vanessa-cooper — APPROVED** [review]
Nice! Looks like there are some records in your local DB. Now you can merge the PR, take a quick break and come back to Slack once you’re ready for your next project.

**Pull request merged**
